### ISSUE TITLE
check json export format

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_profile_editor#197]
There seems to be something wrong with the formatting of the JSON exported from the Sinopia Profile Editor.  I imported the Sinopia BF2 Cartographic profile into the dev version of the profile editor, changed 4 things: ID, Title, Date, Author.  Exported the profile.  json output file for download:  https://drive.google.com/file/d/1zfOQFZmsINdnEjFYKTl6-np8WFRxf5tI/view?usp=sharing   Seems to be an error with (lack of) closing statements at the end of the file...

**Comment by ndushay** [comment]
@mcmgee there is a known problem (#187) with URLs having chars such as '#' causing exports to be truncated -- looks like yours ends `"propertyURI":"http://www.w3.org/2000/01/rdf-schema`  which doesn't even have the ending double quote, which makes me think that is the cause here.

Until we get that fixed, can you enter that URI in to profile editor without special chars and hand edit the special chars back in?

Please re-open if that won't work.
