### ISSUE TITLE
CERL QA subauthorities not available / URNs in authority config file not unique for subauthorities?

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_profile_editor#345]
In the stage profile editor, when selecting any of the 4 CERL look-up options from the "Values" pull down menu, they all automatically populate the form to the "CERL imprint (QA)" subauthority label and same URN "urn:ld4p:qa:cerl" and thus I can't get the editor to work for the person or corporate name subauthorities.  It appears to me like maybe the URNs for the CERL subauthorities aren't set-up properly for the subauthorities in the authorities config file: https://github.com/LD4P/sinopia_editor/blob/master/static/authorityConfig.json  

Thanks!

**Comment by jermnelson** [comment]
This problem is easy to replicate and results from CERL authorities all having the same the URI of `urn:ld4p:qa:cerl` in the `authorityConfig.json`. In https://github.com/LD4P/sinopia_profile_editor/blob/a21d67e415aa9841cfcf5eac62b79a04f95baffd/source/html/value.html#L10 the value for the HTML options is being set to the item.uri and since the CERL authorities all share the same uri, any of the selected options are being set to the last CERL entry of `CERL import (QA)`. 

There are a couple of options to fix this issue:
1. Have QA change the URI to unique values for each sub-authority
1. Change how the option value is being set in the controller

**Comment by michelleif** [comment]
did we decide how we are fixing? want to know whether this stays in Sinopia queue or moves to QA queue

**Comment by jermnelson** [comment]
The plan is to try changing the authorityConfig.json to use unique URIs but this issue will need to be prioritized in order to be worked on by the developers.

**Comment by michelleif** [comment]
so until then CERL doesn't work?

**Comment by elrayle** [comment]
This is a very quick fix.  I will take care of it.
