### ISSUE TITLE
Make the profile "save" button perform the JSON "export" to locally available JSON for user

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_profile_editor#4]
Refs LD4P/sinopia#100 Profile Editor respond with only JSON to user

**Comment by kirkhess** [comment]
Why is a user exporting json instead of saving it? 
The export buttons should do this; I think they are not functioning correctly currently. 
You can get the json through the loopback api -> 
http://bibframe.org/bibliomata/profile-edit/#/profile/aa73d751-bb94-4c43-8945-41005cf27d7b
http://bibframe.org/verso/api/configs/aa73d751-bb94-4c43-8945-41005cf27d7b
http://bibframe.org/verso/api/configs?&filter[where][name]=BIBFRAME%202.0%20Sound%20Recording-Audio%20CD

**Comment by jgreben** [comment]
@kirkhess it's just part of our MVP work-plan to not have to maintain any profiles for the users, so "saving" in this context would really mean exporting (or downloading) and thus making some (hopefully minor) modifications along these lines--with some UX work involved; whether this means modifying the save button or something else. Also, I'm not sure if we are going to use the loopback api, or use it in the same way. We may use AWS RDS for this instead.

**Comment by kirkhess** [comment]
I just fixed the export buttons - the difference is if there is an object, array or value which is empty the verbose includes it (i.e. {}, [] or "") while the brief does not.

**Comment by jgreben** [comment]
Thanks @kirkhess good to know. When re-importing with brief, will it re-apply the empty sets as necessary for the profile to function properly? Perhaps we should we just present them with the verbose option to avoid confusion and extra questions about it.

**Comment by kirkhess** [comment]
Everything saves as verbose by default, I don't remember why brief export was in the original SOW but it really isn't that useful. 
See https://github.com/lcnetdev/profile-edit/blob/master/source/assets/js/modules/profile/services/formHandler.service.js

**Comment by ndushay** [comment]
We want tests with good coverage for the new code we'll write to do this our way.

**Comment by jgreben** [comment]
Closing this ticket: broken out into #37, #38, #39
